name = "JPop"
uuid = "9abfff95-bc0f-4122-8446-e1863fb4be3a"
authors = ["Daniel Priego Espinosa", "Jeremy Van Cleve"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
