name = "JPop"
uuid = "9abfff95-bc0f-4122-8446-e1863fb4be3a"
authors = ["Daniel Priego Espinosa", "Jeremy Van Cleve"]
version = "0.1.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
